- name: check_file_exists
  ansible.builtin.copy:
    src: "{{ var_file }}"
    dest: "{{ var_path }}"
    owner: "{{ var_owner }}"
    group: "{{ var_group }}"
    mode: "{{ var_mode }}"
    force: "{{ var_force | default('no') }}"
