version: '2'

services:
  redis:
    image: redis:latest
    container_name: objRedis
    volumes:
      - vol_redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - net_private

volumes:
  vol_redis:

networks:
  net_private:
