---
- hosts: "{{ var_host | default('none') }}"
  become: yes
  tasks:
  - name: Update yum
    shell: yum -y update

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Reboot
    shell: reboot
