---
- hosts: "{{ var_host | default('none') }}"
  become: yes
  tasks:
  - name: Update yum
    shell: yum -y update

  - name: Disable SELinux and reboot
    # Edit SELinux
    #   sudo vi /etc/selinux/config
    # Change
    #   SELINUX=disabled
    shell: reboot
