---
- hosts: "{{ var_host | default('none') }}"
  become: yes
  tasks:
  - name: task_repo_exist
    stat:
      path: /etc/yum.repos.d/docker-ce.repo
    register: repo_exist
  - debug:
      msg: "Path and file not found"
    when: repo_exist.stat.exists == False

  - name: Install pre-requisite packages
    yum:
      name: "{{ item }}"
      state: latest
    loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    when: repo_exist.stat.exists == False

  #
  # Oracle Linux requires the following file:
  #   /etc/yum.repos.d/oraclelinux-developer-ol7.repo
  #     [ol7_developer]
  #     enabled=1
  #

  - name: Add Docker CE repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: not repo_exist.stat.exists

  - name: Install Docker
    yum: name=docker state=latest

  - name: Start and enable the Docker daemon
    service: name=docker state=started enabled=yes
