---
- hosts: "{{ var_host | default('none') }}"
  tasks:
  - name: Push minecraft file
    copy:
      #
      # If src path is a directory, it is copied recursively. If path ends with "/", 
      # only inside contents of that directory are copied to destination.
      #
      src: ../artifact/{{ var_item | default('none') }}.tar.gz
      dest: ~/
      force: no

  - name: Unpack minecraft
    unarchive:
      src: ~/{{ var_item | default('none') }}.tar.gz
      dest: ~/minecraft/
      remote_src: yes
      keep_newer: yes

  # Oracle Linux
  # - Open port in a firewall
  #   sudo systemctl status firewalld
  #   sudo firewall-cmd --list-all
  #   sudo firewall-cmd --list-ports
  #   sudo firewall-cmd --zone=public --permanent --add-port=25565/tcp
  #   sudo firewall-cmd --reload
  # - Subnet and security group
  #   Add ingress rule 0.0.0.0/0 25565

  - name: Set server.port to 25565
    lineinfile:
      path: ~/{{ var_item | default('none') }}/server.properties
      regexp: '^server-port='
      line: server-port=25565

  - name: Set online-mode to false
    lineinfile:
      path: ~/{{ var_item | default('none') }}/server.properties
      regexp: '^online-mode='
      line: online-mode=false

  - name: Set max-tick-time to 999999
    lineinfile:
      path: ~/{{ var_item | default('none') }}/server.properties
      regexp: '^max-tick-time='
      line: max-tick-time=999999
