---
- hosts: "{{ var_host | default('all') }}"
  become: yes
  tasks:
  - name: Ensure compose dir exists
    file: 
      path: /home/{{ ansible_user }}/docker/{{ item }}
      state: directory
      mode: 0755
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"      
      recurse: yes
    loop:
    - nginxpmlite

  - name: Push compose files
    copy:
      src: ../docker/{{ item }}/docker-compose.yml
      dest: /home/{{ ansible_user }}/docker/{{ item }}/docker-compose.yml
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"      
    loop:
    - nginxpmlite

  - name: Deploy compose file
    shell: docker-compose -f /home/{{ ansible_user }}/docker/{{ item }}/docker-compose.yml up
    loop:
    - nginxpmlite
