---
- hosts: "{{ var_host | default('none') }}"
  become: yes
  tasks:
  - name: Ensure compose dir exists
    file: 
      path: /home/{{ ansible_user }}/docker/{{ var_item | default('nginxpmlite') }}
      state: directory
      mode: 0755
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"      
      recurse: yes

  - name: Push compose files
    copy:
      src: ../docker/{{ var_item | default('nginxpmlite') }}/docker-compose.yml
      dest: /home/{{ ansible_user }}/docker/{{ var_item | default('nginxpmlite') }}/docker-compose.yml
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"      

  - name: Deploy compose file
    shell: docker-compose -f /home/{{ ansible_user }}/docker/{{ var_item | default('nginxpmlite') }}/docker-compose.yml up -d
