version: '3.7'
services:
  couchdb:
    # latest, 2.3.1
    image: couchdb
    container_name: objCouchDb
    # expose port
    ports:
      - 5984:5984
    volumes:
      - /home/azureuser/docker/couchdb/data:/opt/couchdb/data:rw
      - /home/azureuser/docker/couchdb/log:/opt/couchdb/log:rw
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    networks:
      - nginxpmlite_net_public

networks:
  nginxpmlite_net_public:
    external: true    
